language: python


branches:
  only:
    - master

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-socket

script:
  - cd tests
  - pytest --cov=../ --disable-socket

after_success:
  - codecov -t e941cc9d-7531-47dc-840d-778d46f83032